version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '8080:8080'
    depends_on:
      - db
      - tarantool
      - rabbitmq
    networks:
      - backend
  db:
    container_name: "db"
    image: postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - backend
  db-slave-one:
    container_name: "db-slave-one"
    image: postgres
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - backend
  tarantool:
    container_name: "tarantool"
    image: tarantool/tarantool:latest
    networks:
      - backend
    ports:
      - '3301:3301'
  redis:
    image: docker.io/bitnami/redis:7.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    networks:
      - backend
    volumes:
      - 'redis_data:/bitnami/redis/data'
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 15672:15672
    networks:
      - backend

volumes:
  healthcheck-volume:
  redis_data:
    driver: local
networks:
  backend:

