version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db
      - tarantool
    networks:
      - backend
  db:
    container_name: "db"
    image: postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - backend
  db-slave-one:
    container_name: "db-slave-one"
    image: postgres
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - backend
  tarantool:
    container_name: "tarantool"
    image: tarantool/tarantool:latest
    networks:
      - backend
    ports:
      - "3301:3301"

volumes:
  healthcheck-volume:
networks:
  backend:

